#!/usr/bin/env python3
"""Process stdin, assumed to contain valid csv, to xhtml."""

import sys
import pandas as pd
from wikitools import printout_html_table_for_xwiki

if __name__ == "__main__":
    try:
        df = pd.read_csv(sys.stdin)  # it accepts a buffer with a .read() method
    except Exception as e:
        raise ApplicationError("String is not valid csv format") from e
    html_str = printout_html_table_for_xwiki(df)
    print(html_str)
