#!/bin/bash

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
    DMENU="dmenu -l 20 $DMENUOPTS"
else
    DMENU='dmenu -i'
fi

cmd=$($DMENU -p "url " $*)
if [ ! -z $"cmd" ] & [ ${#cmd} -gt 3 ]
then
    x-www-browser "${cmd}"
fi
