#!/bin/sh
# Convert all fonts to paths.
# This script is useful to edit figures generated by 
# PyX in inkscape
for origfig in $@; do
    newname=${origfig%.pdf}_outlined.pdf
    echo "${origfig} -> ${newname}"
    # Needs ghostscript 9.15 or newest
    gs -o ${newname} -dNoOutputFonts -sDEVICE=pdfwrite ${origfig}
done


